name: nix
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: DeterminateSystems/nix-installer-action@v9
      - name: install nix
      - run: nix develop
